// <auto-generated />
namespace IT_TRAVEL_GUIDE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tea2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tea2));
        
        string IMigrationMetadata.Id
        {
            get { return "202009132058204_tea2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
